package com.rl.ecps.model;

public class EbShipAddr {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EB_SHIP_ADDR.SHIP_ADDR_ID
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	private Long shipAddrId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EB_SHIP_ADDR.PTL_USER_ID
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	private Long ptlUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EB_SHIP_ADDR.SHIP_NAME
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	private String shipName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EB_SHIP_ADDR.PROVINCE
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	private String province;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EB_SHIP_ADDR.CITY
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EB_SHIP_ADDR.DISTRICT
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	private String district;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EB_SHIP_ADDR.ZIP_CODE
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	private String zipCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EB_SHIP_ADDR.ADDR
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	private String addr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EB_SHIP_ADDR.PHONE
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EB_SHIP_ADDR.DEFAULT_ADDR
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	private Short defaultAddr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EB_SHIP_ADDR.FIXED_PHONE
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	private String fixedPhone;
	
	private String provText;
	
	private String cityText;
	
	private String distText;
	
	

	public String getProvText() {
		return provText;
	}

	public void setProvText(String provText) {
		this.provText = provText;
	}

	public String getCityText() {
		return cityText;
	}

	public void setCityText(String cityText) {
		this.cityText = cityText;
	}

	public String getDistText() {
		return distText;
	}

	public void setDistText(String distText) {
		this.distText = distText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EB_SHIP_ADDR.SHIP_ADDR_ID
	 * @return  the value of EB_SHIP_ADDR.SHIP_ADDR_ID
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	public Long getShipAddrId() {
		return shipAddrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EB_SHIP_ADDR.SHIP_ADDR_ID
	 * @param shipAddrId  the value for EB_SHIP_ADDR.SHIP_ADDR_ID
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	public void setShipAddrId(Long shipAddrId) {
		this.shipAddrId = shipAddrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EB_SHIP_ADDR.PTL_USER_ID
	 * @return  the value of EB_SHIP_ADDR.PTL_USER_ID
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	public Long getPtlUserId() {
		return ptlUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EB_SHIP_ADDR.PTL_USER_ID
	 * @param ptlUserId  the value for EB_SHIP_ADDR.PTL_USER_ID
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	public void setPtlUserId(Long ptlUserId) {
		this.ptlUserId = ptlUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EB_SHIP_ADDR.SHIP_NAME
	 * @return  the value of EB_SHIP_ADDR.SHIP_NAME
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	public String getShipName() {
		return shipName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EB_SHIP_ADDR.SHIP_NAME
	 * @param shipName  the value for EB_SHIP_ADDR.SHIP_NAME
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	public void setShipName(String shipName) {
		this.shipName = shipName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EB_SHIP_ADDR.PROVINCE
	 * @return  the value of EB_SHIP_ADDR.PROVINCE
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EB_SHIP_ADDR.PROVINCE
	 * @param province  the value for EB_SHIP_ADDR.PROVINCE
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	public void setProvince(String province) {
		this.province = province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EB_SHIP_ADDR.CITY
	 * @return  the value of EB_SHIP_ADDR.CITY
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EB_SHIP_ADDR.CITY
	 * @param city  the value for EB_SHIP_ADDR.CITY
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EB_SHIP_ADDR.DISTRICT
	 * @return  the value of EB_SHIP_ADDR.DISTRICT
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	public String getDistrict() {
		return district;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EB_SHIP_ADDR.DISTRICT
	 * @param district  the value for EB_SHIP_ADDR.DISTRICT
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	public void setDistrict(String district) {
		this.district = district;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EB_SHIP_ADDR.ZIP_CODE
	 * @return  the value of EB_SHIP_ADDR.ZIP_CODE
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	public String getZipCode() {
		return zipCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EB_SHIP_ADDR.ZIP_CODE
	 * @param zipCode  the value for EB_SHIP_ADDR.ZIP_CODE
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EB_SHIP_ADDR.ADDR
	 * @return  the value of EB_SHIP_ADDR.ADDR
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	public String getAddr() {
		return addr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EB_SHIP_ADDR.ADDR
	 * @param addr  the value for EB_SHIP_ADDR.ADDR
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	public void setAddr(String addr) {
		this.addr = addr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EB_SHIP_ADDR.PHONE
	 * @return  the value of EB_SHIP_ADDR.PHONE
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EB_SHIP_ADDR.PHONE
	 * @param phone  the value for EB_SHIP_ADDR.PHONE
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EB_SHIP_ADDR.DEFAULT_ADDR
	 * @return  the value of EB_SHIP_ADDR.DEFAULT_ADDR
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	public Short getDefaultAddr() {
		return defaultAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EB_SHIP_ADDR.DEFAULT_ADDR
	 * @param defaultAddr  the value for EB_SHIP_ADDR.DEFAULT_ADDR
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	public void setDefaultAddr(Short defaultAddr) {
		this.defaultAddr = defaultAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EB_SHIP_ADDR.FIXED_PHONE
	 * @return  the value of EB_SHIP_ADDR.FIXED_PHONE
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	public String getFixedPhone() {
		return fixedPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EB_SHIP_ADDR.FIXED_PHONE
	 * @param fixedPhone  the value for EB_SHIP_ADDR.FIXED_PHONE
	 * @mbggenerated  Sun Jul 26 11:22:50 CST 2015
	 */
	public void setFixedPhone(String fixedPhone) {
		this.fixedPhone = fixedPhone;
	}
}